version: "3.8"


services:
  # tag::01_slides[]
  build-slides:
    image: "asciidoctor/docker-asciidoctor"
    volumes:
      - ./:/documents/
    command:
      - "asciidoctor-revealjs"
      - "-a"
      - "revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2"
      - "01-slides/index.adoc"
      - "-o"
      - "docs/index.html"
  # end::01_slides[]
  build-pdf:
    image: "asciidoctor/docker-asciidoctor"
    volumes:
      - ./:/documents/
    command:
      - "asciidoctor-pdf"
      - "01-slides/index.adoc"
      - "-o"
      - "docs/bbl-docker-pour-le-developpeur.pdf"
  build-epub:
    image: "asciidoctor/docker-asciidoctor"
    volumes:
      - ./:/documents/
    command:
      - "asciidoctor-epub3"
      - "01-slides/index.adoc"
      - "-o"
      - "docs/bbl-docker-pour-le-developpeur.epub"
  # tag::07_java_8[]
  07-movie-rental-java-8:
    image: "maven:3-openjdk-8-slim"
    working_dir: "/java-app"
    volumes:
      - "./07-movie-rental-java-8:/java-app"
      - "./.volumes/07-movie-rental-java-8-.m2:/root/.m2"
    command:
      - "mvn"
      #      - "-Dmaven.compiler.source=8"
      - "clean"
      - "test"
  # end::07_java_8[]
  # tag::07_java_17[]
  07-movie-rental-java-17:
    image: "maven:3-openjdk-17-slim"
    working_dir: "/java-app"
    volumes:
      - "./07-movie-rental-java-17:/java-app"
      - "./.volumes/07-movie-rental-java-17-.m2:/root/.m2"
    command:
      - "mvn"
#      - "-Dmaven.compiler.source=17"
      - "clean"
      - "test"
  # end::07_java_17[]