version: "3.8"


services:
  # tag::01_slides[]
  build-slides:
    image: "asciidoctor/docker-asciidoctor"
    volumes:
      - ./:/documents/
    command:
      - "asciidoctor-revealjs"
      - "-a"
      - "revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2"
      - "01-slides/index.adoc"
      - "-o"
      - "docs/index.html"
  # end::01_slides[]
  build-pdf:
    image: "asciidoctor/docker-asciidoctor"
    volumes:
      - ./:/documents/
    command:
      - "asciidoctor-pdf"
      - "01-slides/index.adoc"
      - "-o"
      - "docs/bbl-docker-pour-le-developpeur.pdf"
  build-epub:
    image: "asciidoctor/docker-asciidoctor"
    volumes:
      - ./:/documents/
    command:
      - "asciidoctor-epub3"
      - "01-slides/index.adoc"
      - "-o"
      - "docs/bbl-docker-pour-le-developpeur.epub"