= Docker sur le poste du développeur
:author: Marc Bouvier
:revealjs_controls: true
:revealjs_progress: true
:revealjs_hash: true
:revealjs_theme: solarized
:revealjs_margin: 0.2

== Docker



"Docker est une plateforme permettant de lancer certaines applications dans des conteneurs logiciels."
-- Wikipedia, https://fr.wikipedia.org/wiki/Docker_(logiciel)[docker (logiciel)]

=== Docker Compose

"Docker Compose est un logiciel pour définir et exécuter des applications à partir de multiples conteneurs. Il est basé sur un fichier YAML qui permet de définir les services et les paramètres de leurs créations et ainsi de les démarrer par une commande unique."
-- Wikipedia, Docker (logiciel) : https://fr.wikipedia.org/wiki/Docker_(logiciel)#Outils_associ.C3.A9s[Outils associés]


== Cas d'utilisation


[.notes]
--
Docker et docker-compose peuvent être utiles au quotidien pour les développeurs.

1. Utiliser des outils sans les installer
2. Éviter de polluer son environnement
3. Tester un logiciel compliqué à installer par exemple gitlab
4. Test containers
5. Tester et reproduire l'intégration continue en local
6. Environnements de développement à distance (Vs code remote, gitpod, code server)
7. Lancer des logiciels dont on ne connaît pas la technologie
8. Par exemple springboot si on fait du JavaScript
9. Tester une nouvelle version de langage (ex. java 11 java 17..)
10. Infrastructure éphémère : lancer un serveur pour le temps d'un événement
11. Réduire la différence entre le développement local et le développement déployé (ex depuis windows, exécuter sur linux)
12. Bac à sable
13. Être admin dans un container quand on n'est pas admin de sa machine
--


== 01 Lancer des outils sans les installer

=== Asciidoctor

[.notes]
--
Asciidoctor est un format de markup.
C'est aussi un outil qui permet de générer du contenu.
--

- html
- pdf
- slides
- ebook

=== Démo Asciidoctor

Ces slides footnote:[https://github.com/baldir-fr/bbl-docker-pour-le-developpeur]

`docker-compose.yml`

[source,yml]
----
include::../docker-compose.yml[tag=01_slides]
----


